rocm: Include nccl_ofi_rocm.h in release tarball
nccl_ofi_rocm.h was missing from the noinst_HEADERS list in
include/Makefile.am, causing it to be excluded from release tarballs.
Building from an extracted tarball would fail with:
  fatal error: nccl_ofi_rocm.h: No such file or directory
Add nccl_ofi_rocm.h to noinst_HEADERS so it is included in future
release tarballs.

Signed-off-by: Lindsay Reiser <lindsay.reiser@cornelisnetworks.com>